### ISSUE TITLE
Output IBD0 segments?

### ISSUE THREAD

**Issue by shakeeljessa** [browning-lab/hap-ibd#1]
Hi! First off, thank you for this awesome tool.

My question regards if there is a way to have hap-ibd output IBD0 (maybe called IBS0) segments? ie. segments where there were no shared alleles? Please let me know if I can clarify my question at all.

**Comment by browning-lab** [comment]
No, there is not an option for outputting IBD0 segments.  These segments
would need to be obtained from the output IBD haplotypes segments.

Best regards,

Brian

Brian Browning, PhD
Professor
Department of Medicine,
Division of Medical Genetics
University of Washington

**Comment by shakeeljessa** [comment]
Thanks for the prompt reply!
