### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by alexreg** [browning-lab/hap-ibd#12]
Hello, could you kindly tag a release so I can include a package for this program in the Homebrew Bioscience repository?

**Comment by browning-lab** [comment]
Thank you for this suggestion.  I've added a git annotated tag to the most recent version.

**Comment by alexreg** [comment]
Thanks, that's super. I'll try to get that package accepted now.

**Comment by alexreg** [comment]
[Done](https://github.com/brewsci/homebrew-bio/pull/1701#event-13140330804)

**Comment by browning-lab** [comment]
Great!  Thank you for following up.  I will close this issue now.

Brian Browning
University of Washington
