### ISSUE TITLE
Ask questions about filtering genotype data

### ISSUE THREAD

**Issue by chywish** [browning-lab/hap-ibd#5]
Thank you for the excellent software you developed, I tested it and it works very fast.
I have a question, what should I do with the input genotype data if I want to analyze IBD fragments? 
Whether it is necessary to eliminate individuals with third-pedigree relationships before phasing, as described in the software article？
Can you give me some advice？ thanks

**Comment by browning-lab** [comment]
It is not necessary to eliminate closely-related individuals from your data set.  Please e-mail analysis-related questions directly to the author's e-mail address.
