### ISSUE TITLE
Error: Genetic map has only one map position

### ISSUE THREAD

**Issue by XIAO2Mark** [browning-lab/hap-ibd#8]
Hi, 
Greeting! I got some problems when i run hap-ibd, may i ask if you can help me to check it? details as bellow,
*********************************************
Copyright (C) 2019 Brian L. Browning
Enter "java -jar hap-ibd.jar" to print a list of command line arguments

Program            :  hap-ibd.jar  [ version 1.0, 20May22.818 ]
Start Time         :  09:26 PM HKT on 26 Sep 2022
Max Memory         :  30688 MB

Parameters
  gt               :  phased_all_filtered_snp.vcf.gz
  map              :  phased_snp.map
  out              :  hap-ibd.out
  min-seed         :  2.0
  max-gap          :  1000
  min-extend       :  1.0
  min-output       :  2.0
  min-markers      :  100
  min-mac          :  2
  nthreads         :  48

Exception in thread "main" java.lang.IllegalArgumentException: Genetic map has only one map position: 1	chr1:17397	0	17397
	at vcf.PlinkGenMap.fillMapPositions(PlinkGenMap.java:86)
	at vcf.PlinkGenMap.<init>(PlinkGenMap.java:52)
	at vcf.PlinkGenMap.fromPlinkMapFile(PlinkGenMap.java:116)
	at vcf.GeneticMap.geneticMap(GeneticMap.java:119)
	at hapibd.PbwtIbdDriver.detectIbd(PbwtIbdDriver.java:66)
	at hapibd.HapIbdMain.main(HapIbdMain.java:77)

many thanks.

**Comment by browning-lab** [comment]
Hello,
First, try to diagnose the problem from the error message.  In this case, the error message explains why the program stopped running.  If you are unable to resolve the problem from the error message, please read the paper describing the hap-ibd method to understand how the method works.  If neither of these steps solves the problem, please contact the author (me) by e-mail (not through the GitHub issues channel), and I will try to help.
